### ISSUE TITLE
Plugin is unavailable for IntelliJ 2017.3.5+

### ISSUE THREAD

**Issue by artem-zinnatullin** [elpassion/mainframer-intellij-plugin#182]
Hey guys, my colleague and now I noticed that IntelliJ plugin is not showing up in `Plugins → Browse repositories` in IJ 2017.3.5

Look at https://plugins.jetbrains.com/plugin/9603-mainframer-integration suggests that plugin is not marked as compatible for IJ higher than `173.4301.14`

Current stable release of IJ is:

```
IntelliJ IDEA 2017.3.5 (Community Edition)
Build #IC-173.4674.33, built on March 5, 2018
```

<img width="598" alt="screen shot 2018-03-25 at 12 19 50 pm" src="https://user-images.githubusercontent.com/967132/37879052-eff34456-3026-11e8-8d4a-5a5d13afba6f.png">

Can you please release an update with increased IJ compatibility? 

I'm also curious if you can specify whole branch of IJ like `173.+` as compatible, rather limiting compatibilty to IJ platform Plugin was built against as that seems how it works atm :)

https://github.com/elpassion/mainframer-intellij-plugin/blob/831cf39a0d3cb17255c124a331e23667cc2dc1f0/build.gradle.kts#L45

Thanks!

Kind regards,
Artem

**Comment by ghostbuster91** [comment]
Hi Artem,

Yes of course we can release an update with bumped up version of Intellij Idea, but as you already noticed current approach is laborious since we have to manually release plugin for each new version.

I remember the reason why we did like that. Obviously it was because of compatibility issues. But I am not sure whether we used specific branch or we matched to all new versions.

Anyway I would like to change the approach to match the branch as you suggested.
