### ISSUE TITLE
"Default mainframer tool location" is not obvious

### ISSUE THREAD

**Issue by artem-zinnatullin** [elpassion/mainframer-intellij-plugin#63]
When you click on icon, it asks for folder path, but not for `mainframer.sh` file path. 

Maybe ask for `.sh` file path instead of folder?

Or rename to "Default mainframer tool folder"?

**Comment by pawegio** [comment]
I believe that asking directly for `.sh` file path will be better approach, as long as `Mainframer tool` consists of one file, since filename occasionally might be changed.

**Comment by artem-zinnatullin** [comment]
Well, mainframer is also `.mainframer` folder with configs, so I would vote for specifying `folder` for now. Thoughts?

**Comment by ghostbuster91** [comment]
I think that existence of that folder is irrelevant. It will still be invisible for most of the users. 
On the other hand if somebody would see it, it might be confusing if we would go with `folder` selection.
`Folder` selection is used e.g. for jdk or android sdk, where their folders contains only files specific to particular tool which is not the case with mainframer.
I did this `folder` selection in the past because it was easier than looking for some single file in a project.
Now I think that we should go with single file selection with additional filter (at least file extension filter, but `mainframer.sh` filter looks also good to me).

**Comment by artem-zinnatullin** [comment]
Makes sense, sgtm!
