### ISSUE TITLE
Bundle Kotlin runtime library with the plugin

### ISSUE THREAD

**Issue by pawegio** [elpassion/mainframer-intellij-plugin#92]

**Comment by jozzi05** [comment]
Please refer to:
http://www.jetbrains.org/intellij/sdk/docs/tutorials/kotlin.html

```
Please note that you should not include kotlin-runtime and kotlin-stdlib jars with your plugin because Kotlin guarantees backward- and forward- binary compatibility.
```

**Comment by jozzi05** [comment]
Also refer to: 8fb622193e4b7e1b4d14f9e9c8bf5dba32edb794

**Comment by ghostbuster91** [comment]
@jozzi05 
> Dmitry Kandalov [3:16 PM] 
What is the earliest version of IntelliJ IDEs which supports plugins written in Kotlin?
And since which version Kotlin 1.1 can be used in plugins? :slightly_smiling_face:  
(by “version” I mean build number http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html)

>Dmitry Jemerov [JB] [3:29 PM] 
if you bundle the Kotlin runtime with your plugin, you can use it with any version of IntelliJ, and you can use any version of Kotlin 
>the 1.1 runtime will be bundled starting with 2017.1

**Comment by pawegio** [comment]
Ok, now refer to:
https://kotlinlang.org/docs/reference/compatibility.html#binary-compatibility-warnings

```
This means that you have a dependency on libraries of different versions, for example the 1.1 standard library and the 1.0 reflection library. To prevent subtle errors at runtime, we recommend you to use the same version of all Kotlin libraries. In this case, consider adding an explicit dependency on the 1.1 reflection library.
```

I performed this change due to this error during gradle build:

```Runtime JAR files in the classpath should have the same version.```

**Comment by jozzi05** [comment]
@ghostbuster91 @pawegio if you both agree that this is a good approach, then I'm fine with it.
